[package]
name = "ans-api"
version = "1.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.6.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
snarkvm-console-program = "1.6.0"
snarkvm-console-network = "1.6.0"
snarkvm-ledger-block = "1.6.0"
reqwest = { version = "0.11", features = ["json"] }
lazy_static = "1.5.0"
regex = "1.10.6"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.11"
rust_decimal = {  version = "1.26", features = ["db-tokio-postgres"] }
deadpool-postgres = "0.11.0"
actix-web-prom = "0.7.0"
futures-util = "0.3.28"
base64 = "0.13"
futures = "0.3.28"
actix-governor = "0.5.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tracing-error = "0.2"
color-eyre = "0.6"
dotenv = "0.15.0"
bigdecimal = "0.4"