version: '2'

services:
  postgresql:
    container_name: postgresql
    environment:
      - PGID=1000
      - POSTGRES_DB=ans
      - POSTGRES_PASSWORD=ansPwd
      - POSTGRES_USER=ansUsr
      - PUID=1000
    image: postgres:15.3
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./.db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    environment:
      URL_HOST: https://api.explorer.aleo.org/v1/testnet
      URL_HOSTS: https://api.explorer.aleo.org/v1/testnet
      PROGRAM: aleo_name_service_registry.aleo
      NET_ID: 1
      DATABASE_URL: postgresql://ansUsr:ansPwd@postgresql:5432/ans
      VIRTUAL_HOST: api.aleonames.local
      LOG_STORE: ans
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      LOG_STORE: ans
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
