apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - releases/namespace.yaml
  - releases/deployment.yaml
  - releases/service.yaml
  - releases/ingress.yaml

images:
  - name: ghcr.io/s-t-soft/aleo-name-service-api
    newTag: "latest"