  name: Update Kustomize Image Tag
  on:
    workflow_run:
      workflows:
        - "Build and Push Docker Image"
      types:
        - completed
  jobs:
    update:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install yq
          run: |
            sudo apt-get install -y python3-pip
            pip3 install yq

        - name: Update Kustomize image tag
          run: |
            yq eval '.images[0].newTag = "${{ github.run_id }}"' -i kustomization.yaml

        - name: Commit changes
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add kustomization.yaml
            git commit -m "Update image tag to ${{ github.run_id }}"
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}